Array.closest = (function () {
    function dist(s, t) {
        if (!s.length || !t.length) return 0;
        return dist(s.slice(2), t.slice(2)) +
            Math.abs(parseInt(s.slice(0, 2), 16) - parseInt(t.slice(0, 2), 16));
    }

    return function (arr, str) {
        var min = 0xffffff;
        var best, current, i;
        for (i = 0; i < arr.length; i++) {
            current = dist(arr[i], str)
            if (current < min) {
                min = current
                best = arr[i];
            }
        }
        return best;
    };
}());


// http://www.crockford.com/wrrrld/color.html
var cssColorsIds = {
    '191970': 'midnightblue',
    '696969': 'dimgray',
    '708090': 'slategray',
    '778899': 'lightslategray',
    '800000': 'maroon',
    '800080': 'purple',
    '808000': 'olive',
    '808080': 'gray',
    'f0f8ff': 'aliceblue',
    'faebd7': 'antiquewhite',
    '00ffff': 'cyan',
    '7fffd4': 'aquamarine',
    'f0ffff': 'azure',
    'f5f5dc': 'beige',
    'ffe4c4': 'bisque',
    '000000': 'black',
    'ffebcd': 'blanchedalmond',
    '0000ff': 'blue',
    '8a2be2': 'blueviolet',
    'a52a2a': 'brown',
    'deb887': 'burlywood',
    '5f9ea0': 'cadetblue',
    '7fff00': 'chartreuse',
    'd2691e': 'chocolate',
    'ff7f50': 'coral',
    '6495ed': 'cornflowerblue',
    'fff8dc': 'cornsilk',
    'dc143c': 'crimson',
    '00008b': 'darkblue',
    '008b8b': 'darkcyan',
    'b8860b': 'darkgoldenrod',
    'a9a9a9': 'darkgray',
    '006400': 'darkgreen',
    'bdb76b': 'darkkhaki',
    '8b008b': 'darkmagenta',
    '556b2f': 'darkolivegreen',
    'ff8c00': 'darkorange',
    '9932cc': 'darkorchid',
    '8b0000': 'darkred',
    'e9967a': 'darksalmon',
    '8fbc8f': 'darkseagreen',
    '483d8b': 'darkslateblue',
    '2f4f4f': 'darkslategray',
    '00ced1': 'darkturquoise',
    '9400d3': 'darkviolet',
    'ff1493': 'deeppink',
    '00bfff': 'deepskyblue',
    '1e90ff': 'dodgerblue',
    'b22222': 'firebrick',
    'fffaf0': 'floralwhite',
    '228b22': 'forestgreen',
    'ff00ff': 'magenta',
    'dcdcdc': 'gainsboro',
    'f8f8ff': 'ghostwhite',
    'ffd700': 'gold',
    'daa520': 'goldenrod',
    '008000': 'green',
    'adff2f': 'greenyellow',
    'f0fff0': 'honeydew',
    'ff69b4': 'hotpink',
    'cd5c5c': 'indianred',
    '4b0082': 'indigo',
    'fffff0': 'ivory',
    'f0e68c': 'khaki',
    'e6e6fa': 'lavender',
    'fff0f5': 'lavenderblush',
    '7cfc00': 'lawngreen',
    'fffacd': 'lemonchiffon',
    'add8e6': 'lightblue',
    'f08080': 'lightcoral',
    'e0ffff': 'lightcyan',
    'fafad2': 'lightgoldenrodyellow',
    'd3d3d3': 'lightgray',
    '90ee90': 'lightgreen',
    'ffb6c1': 'lightpink',
    'ffa07a': 'lightsalmon',
    '20b2aa': 'lightseagreen',
    '87cefa': 'lightskyblue',
    'b0c4de': 'lightsteelblue',
    'ffffe0': 'lightyellow',
    '00ff00': 'lime',
    '32cd32': 'limegreen',
    'faf0e6': 'linen',
    '66cdaa': 'mediumaquamarine',
    '0000cd': 'mediumblue',
    'ba55d3': 'mediumorchid',
    '9370db': 'mediumpurple',
    '3cb371': 'mediumseagreen',
    '7b68ee': 'mediumslateblue',
    '00fa9a': 'mediumspringgreen',
    '48d1cc': 'mediumturquoise',
    'c71585': 'mediumvioletred',
    'f5fffa': 'mintcream',
    'ffe4e1': 'mistyrose',
    'ffe4b5': 'moccasin',
    'ffdead': 'navajowhite',
    '000080': 'navy',
    'fdf5e6': 'oldlace',
    '6b8e23': 'olivedrab',
    'ffa500': 'orange',
    'ff4500': 'orangered',
    'da70d6': 'orchid',
    'eee8aa': 'palegoldenrod',
    '98fb98': 'palegreen',
    'afeeee': 'paleturquoise',
    'db7093': 'palevioletred',
    'ffefd5': 'papayawhip',
    'ffdab9': 'peachpuff',
    'cd853f': 'peru',
    'ffc0cb': 'pink',
    'dda0dd': 'plum',
    'b0e0e6': 'powderblue',
    'ff0000': 'red',
    'bc8f8f': 'rosybrown',
    '4169e1': 'royalblue',
    '8b4513': 'saddlebrown',
    'fa8072': 'salmon',
    'f4a460': 'sandybrown',
    '2e8b57': 'seagreen',
    'fff5ee': 'seashell',
    'a0522d': 'sienna',
    'c0c0c0': 'silver',
    '87ceeb': 'skyblue',
    '6a5acd': 'slateblue',
    'fffafa': 'snow',
    '00ff7f': 'springgreen',
    '4682b4': 'steelblue',
    'd2b48c': 'tan',
    '008080': 'teal',
    'd8bfd8': 'thistle',
    'ff6347': 'tomato',
    '40e0d0': 'turquoise',
    'ee82ee': 'violet',
    'f5deb3': 'wheat',
    'ffffff': 'white',
    'f5f5f5': 'whitesmoke',
    'ffff00': 'yellow',
    '9acd32': 'yellowgreen'
};

var cssColorNames = {
    '191970': 'Midnight Blue',
    '696969': 'Dim Gray',
    '708090': 'Slate Gray',
    '778899': 'Light Slate Gray',
    '800000': 'Maroon',
    '800080': 'Purple',
    '808000': 'Olive',
    '808080': 'Gray',
    'f0f8ff': 'Alice Blue',
    'faebd7': 'Antique White',
    '00ffff': 'Cyan',
    '7fffd4': 'Aquamarine',
    'f0ffff': 'Azure',
    'f5f5dc': 'Beige',
    'ffe4c4': 'Bisque',
    '000000': 'Black',
    'ffebcd': 'Blanched Almond',
    '0000ff': 'Blue',
    '8a2be2': 'Blue Violet',
    'a52a2a': 'Brown',
    'deb887': 'Burlywood',
    '5f9ea0': 'Cadet Blue',
    '7fff00': 'Chartreuse',
    'd2691e': 'Chocolate',
    'ff7f50': 'Coral',
    '6495ed': 'Cornflower Blue',
    'fff8dc': 'Cornsilk',
    'dc143c': 'Crimson',
    '00008b': 'Dark Blue',
    '008b8b': 'Dark Cyan',
    'b8860b': 'Dark Goldenrod',
    'a9a9a9': 'Dark Gray',
    '006400': 'Dark Green',
    'bdb76b': 'Dark Khaki',
    '8b008b': 'Dark Magenta',
    '556b2f': 'Dark Olive Green',
    'ff8c00': 'Dark Orange',
    '9932cc': 'Dark Orchid',
    '8b0000': 'Dark Red',
    'e9967a': 'Dark Salmon',
    '8fbc8f': 'Dark Sea Green',
    '483d8b': 'Dark Slate Blue',
    '2f4f4f': 'Dark Slate Gray',
    '00ced1': 'Dark Turquoise',
    '9400d3': 'Dark Violet',
    'ff1493': 'Deep Pink',
    '00bfff': 'Deep Sky Blue',
    '1e90ff': 'Dodger Blue',
    'b22222': 'Firebrick',
    'fffaf0': 'Floral White',
    '228b22': 'Forest Green',
    'ff00ff': 'Magenta',
    'dcdcdc': 'Gainsboro',
    'f8f8ff': 'Ghost White',
    'ffd700': 'Gold',
    'daa520': 'Goldenrod',
    '008000': 'Green',
    'adff2f': 'Green Yellow',
    'f0fff0': 'Honeydew',
    'ff69b4': 'Hot Pink',
    'cd5c5c': 'Indian Red',
    '4b0082': 'Indigo',
    'fffff0': 'Ivory',
    'f0e68c': 'Khaki',
    'e6e6fa': 'Lavender',
    'fff0f5': 'Lavender Blush',
    '7cfc00': 'Lawn Green',
    'fffacd': 'Lemon Chiffon',
    'add8e6': 'Light Blue',
    'f08080': 'Light Coral',
    'e0ffff': 'Light Cyan',
    'fafad2': 'Light Goldenrod Yellow',
    'd3d3d3': 'Light Gray',
    '90ee90': 'Light Green',
    'ffb6c1': 'Light Pink',
    'ffa07a': 'Light Salmon',
    '20b2aa': 'Light Sea Green',
    '87cefa': 'Light Sky Blue',
    'b0c4de': 'Light Steel Blue',
    'ffffe0': 'Light Yellow',
    '00ff00': 'Lime',
    '32cd32': 'Lime Green',
    'faf0e6': 'Linen',
    '66cdaa': 'Medium Aquamarine',
    '0000cd': 'Medium Blue',
    'ba55d3': 'Medium Orchid',
    '9370db': 'Medium Purple',
    '3cb371': 'Medium Sea Green',
    '7b68ee': 'Medium Slate Blue',
    '00fa9a': 'Medium Spring Green',
    '48d1cc': 'Medium Turquoise',
    'c71585': 'Medium Violet Red',
    'f5fffa': 'Mint Cream',
    'ffe4e1': 'Misty Rose',
    'ffe4b5': 'Moccasin',
    'ffdead': 'Navajo White',
    '000080': 'Navy',
    'fdf5e6': 'Old Lace',
    '6b8e23': 'Olive Drab',
    'ffa500': 'Orange',
    'ff4500': 'Orange Red',
    'da70d6': 'Orchid',
    'eee8aa': 'Pale Goldenrod',
    '98fb98': 'Pale Green',
    'afeeee': 'Pale Turquoise',
    'db7093': 'Pale Violet Red',
    'ffefd5': 'Papaya Whip',
    'ffdab9': 'Peach Puff',
    'cd853f': 'Peru',
    'ffc0cb': 'Pink',
    'dda0dd': 'Plum',
    'b0e0e6': 'Powder Blue',
    'ff0000': 'Red',
    'bc8f8f': 'Rosy Brown',
    '4169e1': 'Royal Blue',
    '8b4513': 'Saddle Brown',
    'fa8072': 'Salmon',
    'f4a460': 'Sandy Brown',
    '2e8b57': 'Sea Green',
    'fff5ee': 'Seashell',
    'a0522d': 'Sienna',
    'c0c0c0': 'Silver',
    '87ceeb': 'Sky Blue',
    '6a5acd': 'Slate Blue',
    'fffafa': 'Snow',
    '00ff7f': 'Spring Green',
    '4682b4': 'Steel Blue',
    'd2b48c': 'Tan',
    '008080': 'Teal',
    'd8bfd8': 'Thistle',
    'ff6347': 'Tomato',
    '40e0d0': 'Turquoise',
    'ee82ee': 'Violet',
    'f5deb3': 'Wheat',
    'ffffff': 'White',
    'f5f5f5': 'White Smoke',
    'ffff00': 'Yellow',
    '9acd32': 'Yellow Green'
}

var colorsArrNames = [];
for(var key in colorsFullList) {
    colorsArrNames.push(key);
}

function getClosestColor(hex) {
    var hexToSearch = hex.replace('#', '');
    hexToSearch = hex.length < 6 ? hexToSearch.replace(/(.)/g, '$1$1') : hexToSearch;
    let closestHex = Array.closest(colorsArrNames, hexToSearch)
    return colorsFullList[closestHex];
}